import "dotenv/config";
import express from "express";
import cors from "cors";
import helmet from "helmet";
import cookieParser from "cookie-parser";
import rateLimit from "express-rate-limit";
import { connectDB } from "./config/db.js";
import auth from "./routes/auth.js";
import user from "./routes/user.js";
import characters from "./routes/characters.js";
import chat from "./routes/chat.js";
import memories from "./routes/memories.js";
import admin from "./routes/admin.js";
import { errorHandler } from "./middleware/error.js";

const app=express();
app.use(helmet());
app.use(cors({origin:process.env.CLIENT_URL||"http://localhost:5173",credentials:true}));
app.use(express.json({limit:"1mb"}));
app.use(cookieParser());
app.use(rateLimit({windowMs:15*60*1000,max:300,standardHeaders:true,legacyHeaders:false}));
app.get("/health",(req,res)=>res.json({ok:true,service:"gf-ai-api"}));
app.use("/api/auth",auth);
app.use("/api/user",user);
app.use("/api/characters",characters);
app.use("/api/chat",chat);
app.use("/api/memories",memories);
app.use("/api/admin",admin);
app.use(errorHandler);

const port=process.env.PORT||5000;
connectDB().then(()=>app.listen(port,()=>console.log(`GF AI API listening on ${port}`))).catch(err=>{console.error(err);process.exit(1)});
