import React,{useEffect,useState} from "react";
import {Routes,Route,Link,useNavigate} from "react-router-dom";
import {Heart,Home,MessageCircle,Users,Image as ImageIcon,Settings,LogOut,Sparkles,Menu,X,Mic,Send} from "lucide-react";
import {api,auth} from "./services/api";

const presets=["Caring","Cute","Funny","Intelligent","Confident","Calm","Study Partner","Gamer"];
function Shell({children}){const [open,setOpen]=useState(false);const nav=[["/","Home",Home],["/chats","Chats",MessageCircle],["/characters","Characters",Users],["/gallery","Gallery",ImageIcon],["/settings","Settings",Settings]];return <div className="app"><aside className={open?"sidebar open":"sidebar"}><div className="brand"><div className="brandmark"><Heart size={18} fill="currentColor"/></div><b>GF AI</b><button className="icon mobileOnly" onClick={()=>setOpen(false)}><X/></button></div>{nav.map(([to,label,Icon])=><Link onClick={()=>setOpen(false)} className="navitem" to={to} key={to}><Icon size={19}/>{label}</Link>)}<button className="navitem logout" onClick={async()=>{await auth.logout();location.href="/login"}}><LogOut size={19}/>Logout</button></aside>{open&&<div className="scrim" onClick={()=>setOpen(false)}/>}<main className="main"><header className="topbar"><button className="icon mobileOnly" onClick={()=>setOpen(true)}><Menu/></button><span className="eyebrow">GF AI • PREMIUM COMPANION</span><div className="topactions"><Link className="pill" to="/characters">Create GF</Link></div></header>{children}</main><nav className="bottomnav">{nav.map(([to,label,Icon])=><Link to={to} key={to}><Icon size={19}/><small>{label}</small></Link>)}</nav></div>}

function Landing(){return <div className="landing"><div className="hero"><div><div className="badge"><Sparkles size={15}/> Your AI. Your Companion.</div><h1>Meet a companion that<br/><span>feels uniquely yours.</span></h1><p>Build a fictional adult AI companion with a personality, memory and conversation style designed around you.</p><div className="actions"><Link className="primary" to="/register">Create Your AI Companion</Link><Link className="secondary" to="/login">Start Chatting</Link></div></div><div className="orb"><div className="orbcore">💗</div><div className="orbglow"/></div></div><section className="featuregrid">{[["💬","Natural conversations","Thoughtful, contextual AI chat."],["🧠","Persistent memory","Control what your companion remembers."],["🎙️","Voice ready","Browser and server voice adapters."],["🖼️","Creative gallery","Moderated image generation architecture."],["📚","Study mode","A focused educational experience."],["🔒","Privacy first","Secure sessions and server-side secrets."]].map(x=><div className="glass card" key={x[1]}><div className="emoji">{x[0]}</div><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</section></div>}

function Auth({register=false}){const [form,setForm]=useState({email:"",username:"",password:""});const [error,setError]=useState("");const nav=useNavigate();const submit=async e=>{e.preventDefault();setError("");try{if(register)await auth.register(form);else await auth.login(form);nav("/")}catch(e){setError(e.message)}};return <div className="center"><form className="glass auth card" onSubmit={submit}><div className="brand large"><div className="brandmark"><Heart size={22} fill="currentColor"/></div><b>GF AI</b></div><h2>{register?"Create your account":"Welcome back"}</h2><p className="muted">{register?"Build your private AI companion space.":"Continue your conversations."}</p>{register&&<input placeholder="Username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/>}<input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input type="password" placeholder="Password (8+ characters)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<div className="error">{error}</div>}<button className="primary wide">{register?"Create account":"Login"}</button><p className="muted">{register?"Already have an account? ":"Need an account? "}<Link to={register?"/login":"/register"}>{register?"Login":"Register"}</Link></p></form></div>}

function Dashboard(){return <Shell><section className="dashboard"><div className="welcome glass"><div><span className="eyebrow">YOUR PRIVATE SPACE</span><h1>Good to see you. 💗</h1><p>Choose a companion or create someone new to start a conversation.</p><Link className="primary" to="/characters">Create your GF</Link></div><div className="welcomeorb">✨</div></div><div className="sectionhead"><h2>Everything in one place</h2></div><div className="featuregrid">{[["💬","Chats","Continue conversations with your companions.","/chats"],["👩","Characters","Create multiple fictional adult companions.","/characters"],["🧠","Memory","Review and control saved context.","/settings"],["🖼️","Gallery","Your generated creative collection.","/gallery"]].map(x=><Link className="glass card" to={x[3]} key={x[1]}><div className="emoji">{x[0]}</div><h3>{x[1]}</h3><p>{x[2]}</p></Link>)}</div></section></Shell>}

function Characters(){const [chars,setChars]=useState([]);const [form,setForm]=useState({name:"",adult:true,personality:"Caring",greeting:"Hi! I'm happy to chat with you. 💗"});const [selected,setSelected]=useState(null);const load=()=>api("/characters").then(d=>setChars(d.characters));useEffect(()=>{load().catch(()=>{})},[]);const create=async e=>{e.preventDefault();await api("/characters",{method:"POST",body:JSON.stringify(form)});setForm({...form,name:""});load()};return <Shell><section><div className="sectionhead"><div><span className="eyebrow">CHARACTER STUDIO</span><h1>Your companions</h1></div></div><div className="split"><form className="glass card builder" onSubmit={create}><h2>Create a GF</h2><input required placeholder="Character name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><label>Personality</label><div className="chips">{presets.map(p=><button type="button" className={form.personality===p?"chip active":"chip"} onClick={()=>setForm({...form,personality:p})} key={p}>{p}</button>)}</div><textarea placeholder="Greeting" value={form.greeting} onChange={e=>setForm({...form,greeting:e.target.value})}/><label className="check"><input type="checkbox" checked={form.adult} onChange={e=>setForm({...form,adult:e.target.checked})}/> Fictional adult character setting</label><button className="primary wide" disabled={!form.adult}>Save companion</button></form><div className="cards">{chars.map(c=><div className="glass character card" key={c._id}><div className="avatar">{c.avatar?<img src={c.avatar}/>:c.name?.[0]||"💗"}</div><div><h3>{c.name}</h3><p>{c.personality}</p><Link className="secondary" to={"/chat/"+c._id}>Chat</Link></div></div>)}{!chars.length&&<div className="glass empty">No companions yet. Create your first one.</div>}</div></div></section></Shell>}

import {useParams} from "react-router-dom";
function ChatPage(){const {id}=useParams();const [character,setCharacter]=useState(null),[text,setText]=useState(""),[messages,setMessages]=useState([]),[loading,setLoading]=useState(false),[conversationId,setConversationId]=useState();useEffect(()=>{api("/characters").then(d=>setCharacter(d.characters.find(c=>c._id===id))).catch(()=>{})},[id]);const send=async e=>{e.preventDefault();if(!text.trim()||loading)return;const content=text;setText("");setMessages(m=>[...m,{role:"user",content}]);setLoading(true);try{const d=await api("/chat",{method:"POST",body:JSON.stringify({characterId:id,conversationId,content})});setConversationId(d.conversationId);setMessages(m=>[...m,d.message])}catch(e){setMessages(m=>[...m,{role:"assistant",content:"Sorry, something went wrong. Please try again."}])}finally{setLoading(false)}};return <Shell><section className="chatpage"><div className="chathead glass"><div className="avatar">{character?.name?.[0]||"💗"}</div><div><b>{character?.name||"Your companion"}</b><small>● {character?.mood||"calm"} • fictional AI</small></div><button className="icon"><Mic/></button></div><div className="messages">{messages.length===0&&<div className="chatwelcome"><div className="bigavatar">💗</div><h2>{character?.greeting||"Start a conversation."}</h2><p>Affectionate, supportive and non-explicit by design.</p></div>}{messages.map((m,i)=><div className={m.role==="user"?"msg user":"msg"} key={i}>{m.content}</div>)}{loading&&<div className="msg typing"><i/><i/><i/></div>}</div><form className="composer glass" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Message your companion…" maxLength={12000}/><button className="send" aria-label="Send"><Send size={19}/></button></form></section></Shell>}

function Simple({title,icon,body}){return <Shell><section><span className="eyebrow">GF AI</span><h1>{icon} {title}</h1><div className="glass card empty">{body}</div></section></Shell>}
function Settings(){const [s,setS]=useState({theme:"dark",accentColor:"#ff4fa3",memoryEnabled:true,autoPlayVoice:false,enterToSend:true,language:"en"});useEffect(()=>{api("/user/settings").then(d=>d.settings&&setS(d.settings)).catch(()=>{})},[]);const save=async k=>{const next={...s,[k]:!s[k]};setS(next);await api("/user/settings",{method:"PATCH",body:JSON.stringify({[k]:next[k]})})};return <Shell><section><span className="eyebrow">PREFERENCES</span><h1>Settings</h1><div className="settings glass card">{[["memoryEnabled","Memory"],["autoPlayVoice","Auto-play voice"],["enterToSend","Enter to send"]].map(([k,l])=><button className="setting" onClick={()=>save(k)} key={k}><span>{l}<small>Control this preference across sessions.</small></span><span className={s[k]?"toggle on":"toggle"}>{s[k]?"ON":"OFF"}</span></button>)}</div></section></Shell>}

export default function App(){return <Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<Auth/>}/><Route path="/register" element={<Auth register/>}/><Route path="/characters" element={<Characters/>}/><Route path="/chat/:id" element={<ChatPage/>}/><Route path="/chats" element={<Simple title="Chats" icon="💬" body="Your conversations will appear here after you start chatting."/>}/><Route path="/gallery" element={<Simple title="Gallery" icon="🖼️" body="Generated images will appear here when an image provider is configured."/>}/><Route path="/settings" element={<Settings/>}/><Route path="*" element={<Simple title="404" icon="🧭" body="Page not found."/>}/></Routes>}

